
content:
  - name: repertorio
    label: Repertorio
    type: collection
    path: repertorio
    format: json
    fields:
      - name: title
        label: Titolo
        type: string
        required: true
      - name: artist
        label: Artista
        type: string
      - name: category
        label: Categoria
        type: select
        options:
          values:
            - name: internazionale
              label: Rock internazionale
            - name: italiano
              label: Rock italiano

  - name: band
    label: La Band
    type: collection
    path: band
    format: json
    fields:
      - name: title
        label: Nome
        type: string
        required: true
      - name: role
        label: Strumento / ruolo
        type: string
        required: true
      - name: description
        label: Breve descrizione
        type: text
      - name: photo
        label: Fotografia
        type: image

